### ISSUE TITLE
Can't resolve tlock-js

### ISSUE THREAD

**Issue by ratankaliani** [drand/tlock-js#23]
I'm currently trying to use tlock-js for a small project I'm working on, but I'm unable to get the module installed correctly (getting a module not found: can't resolve tlock-js error). Are there any additional parameters I should be aware of beyond those listed on the npmjs page in order to use tlock-js?

**Comment by CluEleSsUK** [comment]
I'll look into this now!

**Comment by CluEleSsUK** [comment]
Have replicated it - I think maybe the bundling is slightly incorrect; will push a fix shortly!

**Comment by CluEleSsUK** [comment]
Have raised a PR here: https://github.com/drand/tlock-js/pull/24

**Comment by ratankaliani** [comment]
Awesome - thank you!
