### ISSUE TITLE
Support for modern web browser without polyfills

### ISSUE THREAD

**Issue by wighawag** [drand/tlock-js#6]
Currently when using tlock-js in browser, it fails at runtime with

`ReferenceError: Buffer is not defined`

It would be great to use something that work for both browser and node env

**Comment by CluEleSsUK** [comment]
Hi wighawag,

Are you using a bundler like webpack or parcel, or just importing straight in a `<script>` tag?
`tlock-js` does have a dependency on [this polyfill](https://www.npmjs.com/package/buffer) - so I'm surprised it doesn't work out of the box, but perhaps I've misconfigured something.

**Comment by CluEleSsUK** [comment]
Aha okay, perhaps I ought to export `Buffer` from timelock itself.  I also noticed that the default js generated uses `require` - I think I can configure some flags in parcel to output something more generic!

**Comment by wighawag** [comment]
Hi @CluEleSsUK I am using vite.js and it does not add any polyfill by default
as a workaround I added the `buffer` package and it works 

Not sure what the best way forward, but I thought they were alternative to add a buffer polyfill and simply have different code path for browser and node. I think ethers.js does it and do not require any external dependency.

**Comment by CluEleSsUK** [comment]
haven't heard of vite before, looks cool!

100% in agreement this should work out of the box in both browser and node though (and probably deno too !).
We're prepping for a mainnet ceremony over the next few weeks so I don't know if I will ship a fix this week, but hopefully next or the one after!

**Comment by CluEleSsUK** [comment]
I've raised a PR that should hopefully fix your issues! I tested with vite and came across another config option that needed to be set with relation to bigints - have detailed it in the readme.  Let me know if it works for you.
https://github.com/drand/tlock-js/pull/8
